import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from 'next/font/local'
import Navbar from "./components/navbar";
import UpperNavbar from "./components/navbar/UpperNavbar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const helveticaNeue = localFont({
  src:[
    {
      path: '/fonts/HelveticaNeue-Light.otf',
      weight: '200',
      style: 'light',
    },
    {
      path: '/fonts/HelveticaNeue-Regular.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '/fonts/HelveticaNeue-Medium.otf',
      weight: '600',
      style: 'medium',
    },
    {
      path: '/fonts/HelveticaNeue-Bold.otf',
      weight: '800',
      style: 'medium',
    },
  ],
  display: 'swap',
  variable: '--font-helvetica-neue',
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Northern Fox",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${helveticaNeue.className} ${geistMono.variable} antialiased`}
      >
        {/* <UpperNavbar /> */}
        <Navbar 
          logoText="Northern Fox"
          showSignIn={true}
          showDemo={true}
        />
        {children}
      </body>
    </html>
  );
}
