import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from 'next/font/local'
import AIWidgetIcon from "./components/helpers/AIWidgetIcon";
import Navbar from "./components/navbar";
import UpperNavbar from "./components/navbar/UpperNavbar";
import "./globals.css";
import { Manrope } from "next/font/google";
import Footer from "./components/Footer";
import { ModalProvider } from "./components/providers/ModalProvider";

export const manrope = Manrope({
  subsets: ["latin","cyrillic"],
  weight: ["400","500","600","700"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const helveticaNeue = localFont({
  src:[
    {
      path: '/fonts/HelveticaNeue-Light.otf',
      weight: '200',
      style: 'light',
    },
    {
      path: '/fonts/HelveticaNeue-Regular.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '/fonts/HelveticaNeue-Medium.otf',
      weight: '600',
      style: 'medium',
    },
    {
      path: '/fonts/HelveticaNeue-Bold.otf',
      weight: '800',
      style: 'medium',
    },
  ],
  display: 'swap',
  variable: '--font-helvetica-neue',
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Northern Fox",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" className="bg-white">
      <body
        className={`${manrope.className} ${geistMono.variable} antialiased`}
      >
        <ModalProvider>
        <Navbar 
          logoText="Northern Fox"
          showSignIn={true}
          showDemo={true}
          demoHref="/contact" 
        />
        <AIWidgetIcon />
        {children}
        <Footer />
        </ModalProvider>
      </body>
    </html>
  );
}
